### ISSUE TITLE
JSON-RPC API 0.8.0 adaptation

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet#613]
- Documentation: 
https://github.com/starkware-libs/starknet-specs/releases/tag/v0.8.0-rc1
- Currently in RC phase: 0.8.0-rc.1
- Subtask PRs should target branch `json-rpc-v0.8.0`
- Requires an adapted Blockifier version (or at least a commit)

## Subtasks

- [x] Error improvements - introduced in #627 
  - failure reason in `getTransactionStatus`
  - structure in execution errors
  - `INSUFFICIENT_MAX_FEE` -> `INSUFFICIENT_RESOURCES_FOR_VALIDATE`
- [ ] Gas consumption changes
- [x] WebSocket API support - introduced in #619
- RPC method additions:
  - [x] `starknet_getCompiledCasm` - introduced in #633
  - [x] `starknet_getStorageProof` - introduced in #659
  - [x] `starknet_getMessagesStatus` - introduced in #621
  - [x] 10 ws-related methods - introduced in several PRs
